spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gaspass
    username: root
    password:
  jpa:
    hibernate.ddl-auto: 'create-drop'
    generate-ddl: true
    show-sql: true
  sql:
    init:
      mode: ALWAYS